quarkus:
  swagger-ui:
    enable: true
  datasource:
    db-kind: mariadb
    username: root
    password: root
    jdbc:
      url: jdbc:mariadb://localhost:3366/userdb
      max-size: 8
      min-size: 2
  hibernate-orm: #https://quarkus.io/guides/hibernate-orm#hibernate-configuration-properties
    database:
      generation: drop-and-create #none, create, drop-and-create, drop, update.
